### ISSUE TITLE
auto-create/renew secrets on deploy

### ISSUE THREAD

**Issue by dennisjbell** [genesis-community/genesis#275]
We should automatically renew credentials when we deploy.  Though there is no reason not to automatically renew the certificates, provide an opt-out configuration in the yaml.

```
certificates:
  self-signed-cert:
    ssl:
      ca: { valid_for: 10y }
      server: 
        valid_for: 1y,
        autorenew: false
        names: [ "${params.external_domain}" ]
```

**Comment by dennisjbell** [comment]
This can be expanded to create missing certificates/credentials if they aren't already in safe (in the similar manner that credhub does this)

**Comment by mrferris** [comment]
Turns out this is a bad idea other than the case when the secrets haven't been created yet, which is accounted for in issue #453
