### ISSUE TITLE
Have add-secrets / rotate-secrets visibly tick through each item

### ISSUE THREAD

**Issue by thomasmitchell** [genesis-community/genesis#299]
Right now, longer sets of credentials appear to be stalling for long periods of time when, in fact, they're generating several 4096-bit RSA keys (which can take awhile). Listing down each item as its being performed (in a style similar to check-secrets) would help the user see that progress is being made.

**Comment by dennisjbell** [comment]
This will be delivered in v2.7.0

**Comment by dennisjbell** [comment]
This was delivered in v2.7.x
