### ISSUE TITLE
Have a Genesis do -- alias-all option would be awesome

### ISSUE THREAD

**Issue by cwb124** [genesis-community/genesis#319]
Just a little automation that allows for example a new jumpbox user to login and hit the ground running by being able to alias and login to all bosh environments that are in the bosh-deployments repo.

**Comment by dennisjbell** [comment]
I concur that this is outside the single-env scope of genesis kits (which is responsible for the `do` functionality via their `addon` hook.

However, I will mark this for documentation of useful tricks.
