### ISSUE TITLE
Empty multi-line prompt_for results in unbound variable

### ISSUE THREAD

**Issue by tjliebel** [genesis-community/genesis#353]
This error is resulting from providing no input to a multi-line `prompt_for`:
```
What tags would you like to be set on the BOSH VM? (leave value empty to end)
1st value >
./hooks/new: line 318: google_tags: unbound variable
Could not create new env snw-gcpeastus-test (in /home/tliebel/bosh-deployments): 'new' hook exited 1
```
The file referred to by the error is in the `bosh-genesis-kit` but it seems to come from the `prompt_for` multi-line functionality (same error observed with a multi-line DNS prompt being left blank). The issue can be worked-around with `if [ -n "$var" ]; then do stuff` in the `bosh-genesis-kit`. Doing that lead me to believe that this comes from the variable falling out of scope or just not being initialized when there is no input in the `prompt_for`.

**Comment by dennisjbell** [comment]
This is a kit issue - please open it for the affected kit if it is still occurring.
