### ISSUE TITLE
Genesis pipelines currently don't work with kit version in a higher level environment file.

### ISSUE THREAD

**Issue by patjones** [genesis-community/genesis#358]
Consider the following: 
Any genesis repo, in this case, Prometheus with:
- vsphere.yml
- vsphere-sandbox.yml
- vsphere-dev.yml

```
kit:
  name:    prometheus
  version: 1.4.0
```
is located in vsphere.yml.
Both kits currently are deployed with version 1.4.0.

Currently, if we change the version in vsphere.yml to 1.5.0 we get the following behavior:
1. Sandbox deploys correctly pulling in the 1.5.0 change
2. It pushed up it's cache and triggers dev
3. Dev has the most recent cache ref as input but deploys with 1.4.0 again and no-op deploys

From looking at the trace is appeared that when genesis runs ci-pipeline-deploy it determines it's version from the local file changes or lack thereof and starts to run blueprint before it looks at the version from .geneiss/cache/

**Comment by dennisjbell** [comment]
Resolved by the series of pipeline improvements leading up to v2.7.30
