### ISSUE TITLE
2.7.x Breakage: Cannot `genesis new` with secret prompts

### ISSUE THREAD

**Issue by jhunt** [genesis-community/genesis#398]
Found this with 2.7.1, trying to init a new proto-BOSH:

```
What IaaS will this BOSH director orchestrate?
  1) VMWare vSphere
  2) Amazon Web Services
  3) Microsoft Azure
  4) Google Cloud Platform
  5) OpenStack
  6) BOSH Warden
Select choice > Amazon Web Services
What AWS region would you like to deploy to?
> foo
What is your AWS Access Key?
> foo
Use of uninitialized value in subroutine entry at /home/ubuntu/.geese/lib/Genesis/Top.pm line 17.
[ERROR] Cannot prompt for secrets outside a kit hook
[ERROR] Could not create new env linode (in ~/ops/bosh-deployments): 'new' hook exited 1
ubuntu@ip-a-w-s:~/ops/bosh-deployments$ genesis -v
Genesis v2.7.1 (9dfa3520a3) build 20200410.063453
```

Did some digging, and found that no matter what, if a `new` hook requires a secret prompt, two things are broken:

1. The call to Top->new is mis-coded as `Top::new`, causing argument shuffling and some bad breakage (where we bless into a path string, instead of a class ref.  D'oh!)
2. When fixing (1) we run into the problem that we cannot `load_env` the environment we are `new`-ing because, well, it doesn't exist yet!  That's the whole point of `genesis new`!!

**Comment by dennisjbell** [comment]
This has been resolved by fixing the identified bug, and by allowing an environment object be be created via environment variables during a call-back during the environment's creation.
