### ISSUE TITLE
wrong secrets rotation command in README.md

### ISSUE THREAD

**Issue by VasylTretiakov** [genesis-community/genesis#400]
Likely
> Rotate credentials for a deployment:
> `genesis secrets us-west-1-sandbox`
should become
Rotate credentials for a deployment:
`genesis rotate-secrets us-west-1-sandbox`

**Comment by jhunt** [comment]
There's a lot more problems with the Genesis commands section of the README.

@dennisjbell do you want to update that section or just rip it out entirely and rely on something like:

```
For more information on how to use Genesis, see:

    genesis help
```
