### ISSUE TITLE
Quickstart section in README.md generated by genesis upon kit initialization lacks proper markdown formatting

### ISSUE THREAD

**Issue by VasylTretiakov** [genesis-community/genesis#410]
I noticed that _README.md_'s `Quickstart` section in the root of each kit's git repo has abnormal formatting (as displayed by github itself).
![non-md readme](https://user-images.githubusercontent.com/3999712/80871065-371e7900-8cb3-11ea-9ebe-bee8e53b3b1a.png)

This seems to be caused by failure to format commands as code blocks in _Top.pm_.
![top_pm](https://user-images.githubusercontent.com/3999712/80871136-9bd9d380-8cb3-11ea-93a9-aa3436920bb7.png)

**Comment by VasylTretiakov** [comment]
I also start wondering if after fixing the _Top.pm_ code there could be a way to re-generate the previously impacted _README.md_s.

**Comment by dennisjbell** [comment]
Fixed in v2.7.30
