### ISSUE TITLE
Adaptive merge breaks some operations

### ISSUE THREAD

**Issue by michaelmccaskill** [genesis-community/genesis#423]
Performing a fresh deploy of my Concourse 3.21.1. Checking secrets using 2.7.26 yields:

```
$ genesis check-secrets main-lab-ops.yml 

Verifying availability of vault 'main-lab-ops' (<REDACTED>)...ok

Parsing kit secrets descriptions ... Internal error: Could not find inject causing error 'secret /secret/main/lab/ops/concourse/database/atc:password not found' during adaptive merge.
This is a bug in Genesis itself.
Please file an issue at https://github.com/starkandwayne/genesis/issues
```

**Comment by bala151187** [comment]
Trying to deploy new vault 1.6.1 and facing below errors:
$ genesis -v
Genesis v2.7.26 (a672a7e20c) build 20201217.051341

Checking secrets using 2.7.26 yields:
$ genesis check-secrets ops.yml

Verifying availability of vault 'inviolable-gaol' (<REDACTED>)...ok

Parsing kit secrets descriptions ... Could not merge ops environment files:

1 error(s) detected:
 - $.instance_groups.vault.networks.0.static_ips: `$.networks` could not be found in the datastructure


Efforts were made to work around resolving the following errors, but if
they caused the above errors, you may be able to partially resolve this
issue by using export GENESIS_UNEVALED_PARAMS=1:

6 error(s) detected:
 - $.instance_groups.vault.jobs.vault.properties.safe.peer.tls.ca: secret /secret/ops/vault/certs/ca:certificate not found
 - $.instance_groups.vault.jobs.vault.properties.safe.peer.tls.certificate: secret /secret/ops/vault/certs/consul:certificate not found
 - $.instance_groups.vault.jobs.vault.properties.safe.peer.tls.key: secret /secret/ops/vault/certs/consul:key not found
 - $.instance_groups.vault.jobs.vault.properties.safe.tls.certificate: secret /secret/ops/vault/certs/vault:certificate not found
 - $.instance_groups.vault.jobs.vault.properties.safe.tls.key: secret /secret/ops/vault/certs/vault:key not found
 - $.instance_groups.vault.networks.0.static_ips: `$.networks` could not be found in the datastructure``

**Comment by dennisjbell** [comment]
The issue here was that the kit had an incorrect-yet-funtioning syntax for `static_ips` -- the syntax should be `(( static_ips <number> <number> ... <number>))` but the kit was using an outdated syntax of `(( static_ips(<number>,<number>,...<number>) ))`. The kit has been fixed.
