### ISSUE TITLE
[ERROR] Could not connect to vault

### ISSUE THREAD

**Issue by haochenhu233** [genesis-community/genesis#472]
Under the following conditions, the same error was received,
- Duplicate safe targets
- Expired GitHub Token

The output and error was as follows:

Verifying availability of vault 'buf-lab' (https://10.128.4.5)...Argument "s" isn't numeric in numeric eq (==) at /Users/haochenhu/.geese/lib/Genesis/Vault.pm line 462.
unreachable

[ERROR] Could not connect to vault

**Comment by norman-abramovitz** [comment]
@haochenhu233  Please update your issue with the command you ran.    Normally people do not know what caused the issue so you write your issue more like

I got the following error:

I was using the command:

Here is some data that might be pertinent.   (list your targets but change sensitive information like the IP address to incorrect or invalid values.

**Comment by dennisjbell** [comment]
This should be fixed by PR #483, which will be part of v2.8.6
