### ISSUE TITLE
proxy must be :ENV or a URI::HTTP

### ISSUE THREAD

**Issue by tpoland** [genesis-community/genesis#484]
When using an Ubuntu Jammy Bastion, the initial deploy of proto-bosh fails on Stemcell upload with the following error message:

```
creating stemcell (bosh-azure-hyperv-ubuntu-bionic-go_agent 1.61):
  CPI 'create_stemcell' method responded with error: CmdError{"type":"Bosh::Clouds::CloudError","message":"Failed to upload page bl``create_page_blob: inspect:#\u003c
	ArgumentError: proxy must be :ENV or a URI::HTTP\u003e
	backtrace:/home/ops/.bosh/installations/383443bb-01a1-4a01-4795-bd614b402691/packages/bosh_azure_cpi/vendor/bundle/ruby/3.1.0/gems/net-http-persistent-4.0.1/lib/net/http/persistent.rb:756:in `proxy='
/home/ops/.bosh/installations/383443bb-01a1-4a01-4795-bd614b402691/packages/bosh_azure_cpi/vendor/bundle/ruby/3.1.0/gems/faraday-net_http_persistent-1.2.0/lib/faraday/adapter/net_http_persistent.rb:26:in `net_http_connection'
```

Genesis CLI sets `http_proxy` and `https_proxy` to `""` when it has not been configured in the manifest which ultimately trickles down into how this version of Net::HTTP::Persistent handles the incoming proxy which fails to exclude "blank" configurations:

```
    @proxy_config = case proxy
       when :ENV      then Net::HTTP::Configuration.new(:proxy => :environment)
       when URI::HTTP then Net::HTTP::Configuration.new(:proxy => proxy.to_s)
       when nil       then # ignore
       else raise ArgumentError, 'proxy must be :ENV or a URI::HTTP'
    end
```

The error condition prevents the stemcell upload from succeeding.

#### Workaround
Deploying a simple squid proxy on the localhost and then setting `http_proxy` and `https_proxy` to pass traffic through allows the upload to succeed.

#### Suggested Fix
Do not set the environment variable for `http_proxy` and `https_proxy` when they are not set in the manifest.

**Comment by wayneeseguin** [comment]
Wild, what a find 👍
