### ISSUE TITLE
genesis manifest --list should work even with missing parameters

### ISSUE THREAD

**Issue by norman-abramovitz** [genesis-community/genesis#512]
Genesis v3.0.0

There is no way to know the values for type and subset unless you first create a kit.   Informational or help style parameters should work even with missing parameters.

% genesis manifest --list

============================================================================================
manifest - Generate a BOSH deployment manifest for an environment to STDOUT.

Usage: genesis <env> manifest [<options...>]

To see full description with arguments and option, run genesis manifest -h

[FATAL] genesis manifest was called incorrectly: genesis manifest --list

genesis v3.0.0-rc.3 (f32e672d24) build 20240430.153023

Adding  "genesis manifest --help --list" would be acceptable as well.

**Comment by dennisjbell** [comment]
The list of valid manifest types and subtypes is dependent on the kit and the environment.  For example, entombed manifest is invalid if the environment is a create-env, and vaultified is invalid if the env doesn't have credhub variables.  That is why the manifest is scoped to target environments.
